//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicineLab.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int BioID { get; set; }
        public int ServiceID { get; set; }
        public Nullable<decimal> Result { get; set; }
        public Nullable<System.DateTime> DateFinished { get; set; }
        public Nullable<bool> Accepted { get; set; }
        public string Status { get; set; }
        public int AnalyzerID { get; set; }
        public int UserID { get; set; }
    
        public virtual Analyzer Analyzer { get; set; }
        public virtual BioMaterial BioMaterial { get; set; }
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
    }
}
