//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicineLab.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientData()
        {
            this.Patient = new HashSet<Patient>();
        }
    
        public int ID { get; set; }
        public string GUID { get; set; }
        public string SocialSecurityNumber { get; set; }
        public string EIN { get; set; }
        public string PassportSerria { get; set; }
        public string PassportNumber { get; set; }
        public int InsuraneTypeID { get; set; }
    
        public virtual InsuraneType InsuraneType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patient { get; set; }
    }
}
