//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicineLab.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public System.DateTime TimeVisited { get; set; }
        public bool Success { get; set; }
    
        public virtual User User { get; set; }
    }
}
